data<-read.csv("CardioGoodFitness.csv")
str(data)
head(data)
head(data$Product)
data$Product<-as.factor(data$Product)
data$Gender<-as.factor(data$Gender)
data$MaritalStatus<-as.factor(data$MaritalStatus)
data$Fitness<-as.factor(data$Fitness)

str(data)
sum(is.na(data))
t1 <- table(data$Product)
t1
round(prop.table(t1),2)
pie(t1)
sort(t1, decreasing = T)[1]
mean(data$Income)
median(data$Income)
min(data$Income)
max(data$Income)
quantile(data$Income)
quantile(data$Income, probs = seq(0.1,0.9, by=0.1))
summary(data)
library(e1071)
